version: '3.7'
services:
  react-bookstore:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
      - "3001:3001"
      - "9229:9229"
    volumes:
      - ./src/:/home/node/src/
      - ./package.json:/home/node/package.json
      - ./public/:/home/node/public/
